FROM python:3.13-rc-alpine

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=true \
    POETRY_CACHE_DIR='/var/cache/pypoetry' \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    PATH=/home/python/.local/bin:$PATH

RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev cargo

WORKDIR /app
COPY ./ /app

RUN adduser -D python && mkdir /var/cache/pypoetry/ && chown python:python /var/cache/pypoetry && chown python:python /app
USER python

ENV PATH="/app/.venv/bin:$PATH"

RUN pip install --no-cache-dir poetry